notifications:
  email:           false

sudo:              required
dist:              trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language:          node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g @angular/cli
  - npm install

script:
  - npm run build

deploy:
  - provider:      script
    skip_cleanup:  true
    script:        npm run ghpages
    on:
      branch:      master

cache:
  directories:
    - node_modules
